version: '2'
# starts 4 docker containers running minio server instances. Each
# minio server's web interface will be accessible on the host at port
# 9001 through 9004.
services:
 minioz21:
  container_name: minioz21
  image: kp/minio:0218d1
  restart: always
  volumes:
   - /home/kp/repltest/2zones/data1:/data
  ports:
   - "9001:9000"
  environment:
   MINIO_ACCESS_KEY: minio
   MINIO_SECRET_KEY: minio123
  command: server http://minioz2{1...4}/data http://minioz2{5...8}/data
 minioz22:
  container_name: minioz22
  image: kp/minio:0218d1
  restart: always
  volumes:
   - /home/kp/repltest/2zones/data2:/data
  ports:
   - "9002:9000"
  environment:
   MINIO_ACCESS_KEY: minio
   MINIO_SECRET_KEY: minio123
  command: server http://minioz2{1...4}/data http://minioz2{5...8}/data
 minioz23:
  container_name: minioz23
  image: kp/minio:0218d1
  volumes:
   - /home/kp/repltest/2zones/data3:/data
  ports:
   - "9003:9000"
  environment:
   MINIO_ACCESS_KEY: minio
   MINIO_SECRET_KEY: minio123
  command: server http://minioz2{1...4}/data http://minioz2{5...8}/data
  restart: on-failure
 minio4:
  container_name: minioz24
  image: kp/minio:0218d1
  volumes:
   - /home/kp/repltest/2zones/data4:/data
  ports:
   - "9004:9000"
  environment:
   MINIO_ACCESS_KEY: minio
   MINIO_SECRET_KEY: minio123
  command: server http://minioz2{1...4}/data http://minioz2{5...8}/data
  restart: on-failure
 minioz25:
  container_name: minioz25
  image: kp/minio:0218d1
  volumes:
   - /home/kp/repltest/2zones/data5:/data
  ports:
   - "9005:9000"
  environment:
   MINIO_ACCESS_KEY: minio
   MINIO_SECRET_KEY: minio123
  command: server http://minioz2{1...4}/data http://minioz2{5...8}/data
  restart: on-failure
 minioz26:
  container_name: minioz26
  image: kp/minio:0218d1
  volumes:
   - /home/kp/repltest/2zones/data6:/data
  ports:
   - "9006:9000"
  environment:
   MINIO_ACCESS_KEY: minio
   MINIO_SECRET_KEY: minio123
  command: server http://minioz2{1...4}/data http://minioz2{5...8}/data
  restart: on-failure
 minioz27:
  container_name: minioz27
  image: kp/minio:0218d1
  volumes:
   - /home/kp/repltest/2zones/data7:/data
  ports:
   - "9007:9000"
  environment:
   MINIO_ACCESS_KEY: minio
   MINIO_SECRET_KEY: minio123
  command: server http://minioz2{1...4}/data http://minioz2{5...8}/data
  restart: on-failure
 minioz28:
  container_name: minioz28
  image: kp/minio:0218d1
  volumes:
   - /home/kp/repltest/2zones/data8:/data
  ports:
   - "9008:9000"
  environment:
   MINIO_ACCESS_KEY: minio
   MINIO_SECRET_KEY: minio123
  command: server http://minioz2{1...4}/data http://minioz2{5...8}/data   
  restart: on-failure
