version: '2'

# starts 4 docker containers running minio server instances. Each
# minio server's web interface will be accessible on the host at port
# 9001 through 9004.
services:
 minioz11:
  container_name: minioz11
  image: kp/minio:0223d1
  restart: always
  volumes:
   - /home/kp/repltest/1zone/data1:/data
  ports:
   - "9009:9000"
  environment:
   MINIO_ACCESS_KEY: minio
   MINIO_SECRET_KEY: minio123
   MINIO_REGION: us-west-1
  command: server http://minioz1{1...4}/data
 minioz12:
  container_name: minioz12
  image: kp/minio:0223d1
  restart: always
  volumes:
   - /home/kp/repltest/1zone/data2:/data
  ports:
   - "9010:9000"
  environment:
   MINIO_ACCESS_KEY: minio
   MINIO_SECRET_KEY: minio123
   MINIO_REGION: us-west-1
  command: server http://minioz1{1...4}/data
 minioz13:
  container_name: minioz13
  image: kp/minio:0223d1
  volumes:
   - /home/kp/repltest/1zone/data3:/data
  ports:
   - "9011:9000"
  environment:
   MINIO_ACCESS_KEY: minio
   MINIO_SECRET_KEY: minio123
   MINIO_REGION: us-west-1
  command: server http://minioz1{1...4}/data
  restart: on-failure
 minioz14:
  container_name: minioz14
  image: kp/minio:0223d1
  volumes:
   - /home/kp/repltest/1zone/data4:/data
  ports:
   - "9012:9000"
  environment:
   MINIO_ACCESS_KEY: minio
   MINIO_SECRET_KEY: minio123
   MINIO_REGION: us-west-1
  command: server http://minioz1{1...4}/data
  restart: on-failure
